#!/usr/bin/env bash
set -euxo pipefail
sed -i -e '/jcenter()/d' ./node_modules/react-native-fabric/android/build.gradle
gsed -i -e '11i\        jcenter()' ./node_modules/react-native-fabric/android/build.gradle
