package updated.mysterium.vpn.database.preferences

enum class SharedPreferencesList(val prefName: String) {
    //Logic parameters
    BALANCE("BALANCE"),
    MIN_BALANCE("MIN_BALANCE"),
    FIRST_BALANCE_PUSH("FIRST_BALANCE_PUSH"),
    SECOND_BALANCE_PUSH("SECOND_BALANCE_PUSH"),
    THIRD_BALANCE_PUSH("THIRD_BALANCE_PUSH"),
    MIN_BALANCE_PUSH("MIN_BALANCE_PUSH"),
    LOGIN("LOGIN"),
    TOP_UP_FLOW("TOP_UP_FLOW"),
    ACCOUNT_CREATED("ACCOUNT_CREATED"),
    TERMS("TERMS"),
    DNS("DNS"),
    IDENTITY_ADDRESS("IDENTITY_ADDRESS"),
    LANGUAGE("LANGUAGE"),
    CONNECTION_HINT("CONNECTION_HINT"),
    IS_NEW_USER("IS_NEW_USER"),
    DARK_MODE("DARK_MODE"),
    PREVIOUS_COUNTRY_CODE("PREVIOUS_COUNTRY_CODE"),
    PREVIOUS_FILTER_ID("PREVIOUS_FILTER_ID"),
    IS_REVIEW_SHOWN("IS_REVIEW_SHOWN"),
    IS_NAT_AVAILABLE("IS_NAT_AVAILABLE"),
    DURATION("DURATION"),
    IS_POP_UP_TO_SHOW("IS_POP_UP_TO_SHOW"),
    IS_NOTIFICATION_TO_SHOW("IS_NOTIFICATION_TO_SHOW"),

    //Pushy parameters
    CRYPTO_PAYMENT("CRYPTO_PAYMENT"),
}
