default_platform(:ios)

platform :ios do
  before_all do
    increment_version_number(version_number: last_git_tag)
    increment_build_number(build_number: number_of_commits)
  end
  
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(scheme: "MysteriumVPN")
    upload_to_testflight
  end
end
