package updated.mysterium.vpn.common.countries

import updated.mysterium.vpn.model.settings.CountryISO
import java.util.*

object CountriesUtil {

    fun getAllResidentCountries(): List<CountryISO> {
        val countries = mutableListOf<CountryISO>()
        val isoCountries = Locale.getISOCountries()
        for (country in isoCountries) {
            val locale = Locale("en", country)
            val code = locale.country
            val name =
                locale.getDisplayCountry(Locale.ENGLISH) // Replace for current selected language
            if (code.isNotEmpty() && name.isNotEmpty()) {
                countries.add(CountryISO(name, code))
            }
        }
        return countries.sortedBy { it.fullName }
    }

    fun getAllPaymentCountries() = listOf(
        CountryISO("Afghanistan", "AF"),
        CountryISO("Albania", "AL"),
        CountryISO("Algeria", "DZ"),
        CountryISO("American Samoa", "AS"),
        CountryISO("Andorra", "AD"),
        CountryISO("Angola", "AO"),
        CountryISO("Anguilla", "AI"),
        CountryISO("Antarctica", "AQ"),
        CountryISO("Antigua and Barbuda", "AG"),
        CountryISO("Argentina", "AR"),
        CountryISO("Armenia", "AM"),
        CountryISO("Aruba", "AW"),
        CountryISO("Australia", "AU"),
        CountryISO("Austria", "AT"),
        CountryISO("Azerbaijan", "AZ"),
        CountryISO("Bahamas", "BS"),
        CountryISO("Bahrain", "BH"),
        CountryISO("Bangladesh", "BD"),
        CountryISO("Barbados", "BB"),
        CountryISO("Belarus", "BY"),
        CountryISO("Belgium", "BE"),
        CountryISO("Belize", "BZ"),
        CountryISO("Benin", "BJ"),
        CountryISO("Bermuda", "BM"),
        CountryISO("Bhutan", "BT"),
        CountryISO("Bolivia", "BO"),
        CountryISO("Bosnia and Herzegovina", "BA"),
        CountryISO("Botswana", "BW"),
        CountryISO("Brazil", "BR"),
        CountryISO("British Virgin Islands", "VG"),
        CountryISO("Brunei", "BN"),
        CountryISO("Bulgaria", "BG"),
        CountryISO("Burkina Faso", "BF"),
        CountryISO("Burundi", "BI"),
        CountryISO("Cambodia", "KH"),
        CountryISO("Cameroon", "CM"),
        CountryISO("Canada", "CA"),
        CountryISO("Cape Verde", "CV"),
        CountryISO("Cayman Island", "KY"),
        CountryISO("Central African Republic", "CF"),
        CountryISO("Chad", "TD"),
        CountryISO("Chile", "CL"),
        CountryISO("China", "CN"),
        CountryISO("Christmas Island", "CX"),
        CountryISO("Cocos (Keeling) Islands", "CC"),
        CountryISO("Colombia", "CO"),
        CountryISO("Comoros", "KM"),
        CountryISO("Cook Islands", "CK"),
        CountryISO("Costa Rica", "CR"),
        CountryISO("Croatia", "HR"),
        CountryISO("Cuba", "CU"),
        CountryISO("Curaçao", "CW"),
        CountryISO("Cyprus", "CY"),
        CountryISO("Czech Republic", "CZ"),
        CountryISO("DR Congo", "CD"),
        CountryISO("Denmark", "DK"),
        CountryISO("Djibouti", "DJ"),
        CountryISO("Dominica", "DM"),
        CountryISO("Dominican Republic", "DO"),
        CountryISO("Ecuador", "EC"),
        CountryISO("Egypt", "EG"),
        CountryISO("El Salvador", "SV"),
        CountryISO("Equatorial Guinea", "GQ"),
        CountryISO("Eritrea", "ER"),
        CountryISO("Estonia", "EE"),
        CountryISO("Ethiopia", "ET"),
        CountryISO("Falkland Islands", "FK"),
        CountryISO("Faroe Islands", "FO"),
        CountryISO("Fiji", "FJ"),
        CountryISO("Finland", "FI"),
        CountryISO("France", "FR"),
        CountryISO("French Polynesia", "PF"),
        CountryISO("French Southern and Antarctic Lands", "TF"),
        CountryISO("Gabon", "GA"),
        CountryISO("Gambia", "GM"),
        CountryISO("Georgia", "GE"),
        CountryISO("Germany", "DE"),
        CountryISO("Ghana", "GH"),
        CountryISO("Gibraltar", "GI"),
        CountryISO("Greece", "GR"),
        CountryISO("Greenland", "GL"),
        CountryISO("Grenada", "GD"),
        CountryISO("Guam", "GU"),
        CountryISO("Guatemala", "GT"),
        CountryISO("Guernsey", "GG"),
        CountryISO("Guinea", "GN"),
        CountryISO("Guinea-Bissau", "GW"),
        CountryISO("Guyana", "GY"),
        CountryISO("Haiti", "HT"),
        CountryISO("Honduras", "HN"),
        CountryISO("Hong Kong", "HK"),
        CountryISO("Hungary", "HU"),
        CountryISO("Iceland", "IS"),
        CountryISO("India", "IN"),
        CountryISO("Indonesia", "ID"),
        CountryISO("Iran", "IR"),
        CountryISO("Iraq", "IQ"),
        CountryISO("Ireland", "IE"),
        CountryISO("Isle of Man", "IM"),
        CountryISO("Israel", "IL"),
        CountryISO("Italy", "IT"),
        CountryISO("Jamaica", "JM"),
        CountryISO("Japan", "JP"),
        CountryISO("Jersey", "JE"),
        CountryISO("Jordan", "JO"),
        CountryISO("Kazakhstan", "KZ"),
        CountryISO("Kenya", "KE"),
        CountryISO("Kiribati", "KI"),
        CountryISO("Kosovo", "XK"),
        CountryISO("Kuwait", "KW"),
        CountryISO("Kyrgyzstan", "KG"),
        CountryISO("Laos", "LA"),
        CountryISO("Latvia", "LV"),
        CountryISO("Lebanon", "LB"),
        CountryISO("Lesotho", "LS"),
        CountryISO("Liberia", "LR"),
        CountryISO("Libya", "LY"),
        CountryISO("Liechtenstein", "LI"),
        CountryISO("Lithuania", "LT"),
        CountryISO("Luxembourg", "LU"),
        CountryISO("Macau", "MO"),
        CountryISO("Macedonia", "MK"),
        CountryISO("Madagascar", "MG"),
        CountryISO("Malawi", "MW"),
        CountryISO("Malaysia", "MY"),
        CountryISO("Maldives", "MV"),
        CountryISO("Mali", "ML"),
        CountryISO("Malta", "MT"),
        CountryISO("Marshall Islands", "MH"),
        CountryISO("Martinique", "MQ"),
        CountryISO("Mauritania", "MR"),
        CountryISO("Mauritius", "MU"),
        CountryISO("Mayotte", "YT"),
        CountryISO("Mexico", "MX"),
        CountryISO("Micronesia", "FM"),
        CountryISO("Moldova", "MD"),
        CountryISO("Monaco", "MC]"),
        CountryISO("Mongolia", "MN"),
        CountryISO("Montenegro", "ME"),
        CountryISO("Montserrat", "MS"),
        CountryISO("Morocco", "MA"),
        CountryISO("Mozambique", "MZ"),
        CountryISO("Myanmar", "MM"),
        CountryISO("Namibia", "NA"),
        CountryISO("Nauru", "NR"),
        CountryISO("Nepal", "NP"),
        CountryISO("Netherlands", "NL"),
        CountryISO("New Caledonia", "NC"),
        CountryISO("New Zealand", "NZ"),
        CountryISO("Nicaragua", "NI"),
        CountryISO("Niger", "NE"),
        CountryISO("Nigeria", "NG"),
        CountryISO("Niue", "NU"),
        CountryISO("Norfolk Island", "NF"),
        CountryISO("North Korea", "KP"),
        CountryISO("Northern Mariana Islands", "MP"),
        CountryISO("Norway", "NO"),
        CountryISO("Oman", "OM"),
        CountryISO("Pakistan", "PK"),
        CountryISO("Palau", "PW"),
        CountryISO("Palestine", "PS"),
        CountryISO("Panama", "PA"),
        CountryISO("Papua New Guinea", "PG"),
        CountryISO("Paraguay", "PY"),
        CountryISO("Peru", "PE"),
        CountryISO("Philippines", "PH"),
        CountryISO("Pitcairn Islands", "PN"),
        CountryISO("Poland", "PL"),
        CountryISO("Portugal", "PT"),
        CountryISO("Puerto Rico", "PR"),
        CountryISO("Qatar", "QA"),
        CountryISO("Republic of the Congo", "CG"),
        CountryISO("Romania", "RO"),
        CountryISO("Russia", "RU"),
        CountryISO("Rwanda", "RW"),
        CountryISO("Réunion", "RE"),
        CountryISO("Saint Barthélemy", "BL"),
        CountryISO("Saint Kitts and Nevis", "KN"),
        CountryISO("Saint Lucia", "LC"),
        CountryISO("Saint Martin", "MF"),
        CountryISO("Saint Vincent and the Grenadines", "VC"),
        CountryISO("Samoa", "WS"),
        CountryISO("San Marino", "SM"),
        CountryISO("Saudi Arabia", "SA"),
        CountryISO("Senegal", "SN"),
        CountryISO("Serbia", "RS"),
        CountryISO("Seychelles", "SC"),
        CountryISO("Sierra Leone", "SL"),
        CountryISO("Singapore", "SG"),
        CountryISO("Sint Maarten", "SX"),
        CountryISO("Slovakia", "SK"),
        CountryISO("Slovenia", "SI"),
        CountryISO("Solomon Islands", "SB"),
        CountryISO("Somalia", "SO"),
        CountryISO("South Africa", "ZA"),
        CountryISO("South Georgia", "GS"),
        CountryISO("South Korea", "KR"),
        CountryISO("South Sudan", "SS"),
        CountryISO("Spain", "ES"),
        CountryISO("Sri Lanka", "LK"),
        CountryISO("Sudan", "SD"),
        CountryISO("Suriname", "SR"),
        CountryISO("Swaziland", "SZ"),
        CountryISO("Sweden", "SE"),
        CountryISO("Switzerland", "CH"),
        CountryISO("Syria", "SY"),
        CountryISO("Taiwan", "TW"),
        CountryISO("Tajikistan", "TJ"),
        CountryISO("Tanzania", "TZ"),
        CountryISO("Thailand", "TH"),
        CountryISO("Togo", "TG"),
        CountryISO("Tokelau", "TK"),
        CountryISO("Tonga", "TO"),
        CountryISO("Trinidad and Tobago", "TT"),
        CountryISO("Tunisia", "TN"),
        CountryISO("Turkey", "TR"),
        CountryISO("Turkmenistan", "TM"),
        CountryISO("Turks and Caicos Islands", "TC"),
        CountryISO("Tuvalu", "TV"),
        CountryISO("Uganda", "UG"),
        CountryISO("Ukraine", "UA"),
        CountryISO("United Arab Emirates", "AE"),
        CountryISO("United Kingdom", "GB"),
        CountryISO("United States", "US"),
        CountryISO("United States Virgin Islands", "VI"),
        CountryISO("Uruguay", "UY"),
        CountryISO("Uzbekistan", "UZ"),
        CountryISO("Vanuatu", "VU"),
        CountryISO("Vatican City", "VA"),
        CountryISO("Venezuela", "VE"),
        CountryISO("Vietnam", "VN"),
        CountryISO("Wallis and Futuna", "WF"),
        CountryISO("Western Sahara", "EH"),
        CountryISO("Yemen", "YE"),
        CountryISO("Zambia", "ZM"),
        CountryISO("Zimbabwe", "ZW"),
        CountryISO("Åland Islands", "AX"),
    )
}
